version: "3.7"
services:
    app:
        build:
            args:
              user: leoves
              uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: potential-crud
        container_name: potential-crud-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - potential-crud
    db:
        image: mysql:5.7
        container_name: potential-crud-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        networks:
            - potential-crud
    nginx:
        image: nginx:1.17-alpine
        container_name: potential-crud-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - potential-crud

networks:
    potential-crud:
        driver: bridge
